# Generated by Django 5.2.8 on 2026-03-31 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_wishlistitem_delete_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlistitems', to='catalog.book'),
        ),
    ]
