# Generated by Django 6.1 on 2026-08-21 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_wishlistitem_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
