# Generated by Django 6.1 on 2026-08-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_delete_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
